BookMe.WebUI/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookMe.WebUI.Models {
    public class SearchViewModel {
        public string MaxAdultCapacity { get; set; }
        public string MaxKidCapacity { get; set; }
        public string MinAdultCapacity { get; set; }
        public string MinKidCapacity { get; set; }
        public string Search { get; set; }
        public string ArrivalDate { get; set; }
        public string DepartureDate { get; set; }
        public string Adults { get; set; }
        public string Kids { get; set; }

    }
}

BookMe.WebUI/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.Domain.Entities;
using BookMe.WebUI.Models;

namespace BookMe.WebUI.Controllers
{
    public class CityController : Controller{
        private ICityRepository _repository;

        public CityController(ICityRepository repository){
            _repository = repository;
        }

        public PartialViewResult MostPopularCities(){
            IDictionary<City, int> mostPopularCities = _repository.MostPopularCities();
            List<CityViewModel> cities = new List<CityViewModel>();
            foreach (var mostPopularCity in mostPopularCities){
                cities.Add(new CityViewModel(){
                    City = mostPopularCity.Key,
                    Count = mostPopularCity.Value
                });
            }
            return PartialView(cities);
        }
    }
}

BookMe.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.WebUI.Models;

namespace BookMe.WebUI.Controllers {
    public class HomeController : Controller{
        private IRoomRepository _repository;

        public HomeController(IRoomRepository repository){
            _repository = repository;
        }
        
        // GET: Home
        public ActionResult Index(){
            return View();
        }

        public PartialViewResult Search(){
            string search = Request.QueryString["search"] ?? "";
            string startDate = Request.QueryString["startDate"] ?? "";
            string endDate = Request.QueryString["endDate"] ?? "";
            string adults = Request.QueryString["adultsInRoom"] ?? "2";
            string kids = Request.QueryString["kidsInRoom"] ?? "0";

            SearchViewModel viewModel = new SearchViewModel() {
                MaxKidCapacity = _repository.BigestKidCapacity().ToString(),
                MaxAdultCapacity = _repository.BigestAdultCapacity().ToString(),
                MinAdultCapacity = _repository.LeastAdultCapacity().ToString(),
                MinKidCapacity = _repository.LeastKidCapacity().ToString(),
                Search = search,
                ArrivalDate = startDate,
                DepartureDate = endDate,
                Adults = adults,
                Kids = kids
            };
            return PartialView(viewModel);
        }
    }
}

BookMe.WebUI/Controllers/HotelController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.Domain.Entities;
using BookMe.WebUI.Filters;
using BookMe.WebUI.Models;
using Ninject.Infrastructure.Language;

namespace BookMe.WebUI.Controllers {
    public class HotelController : Controller {
        private IHotelRepository _repository;
        public int PageSize { get; set; }
        public HotelController(IHotelRepository repository) {
            _repository = repository;
            PageSize = 3;
        }

        public ViewResult List(string search = null, DateTime? startDate = null, DateTime? endDate = null, int? adultsInRoom = null, int kidsInRoom = 0, int page = 1){
            IEnumerable<Hotel> hotels = _repository.GetHotelsFilteredBySearchDatesAdultsKidsInRoom(
                                                        search, startDate, endDate, adultsInRoom, kidsInRoom, page, PageSize);
            HotelListViewModel hotelListViewModel = new HotelListViewModel(){
                Hotels = hotels,
                PagingInfo = new PagingInfo(){
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.GetHotelsFilteredBySearchDatesAdultsKidsInRoom(search, startDate, endDate, adultsInRoom, kidsInRoom).Count()
                },
                SearchParameter = search,
                ChoosenArrival = startDate,
                ChoosenDeparture = endDate,
                KidsCapacity = kidsInRoom,
                AdultsCapacity = adultsInRoom
            };
            return View(hotelListViewModel);
        }
        public PartialViewResult LatestHotels() {
            return PartialView(_repository.LatestHotels());
        }

        public ActionResult Hotel(int id) {
            Hotel hotel = _repository.Get(id);
            if (hotel != null) {
                return View(hotel);
            } else {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

BookMe.WebUI/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.Domain.Entities;
using BookMe.WebUI.Models;
using Newtonsoft.Json;

namespace BookMe.WebUI.Controllers {
    public class RoomController : Controller{
        private IRoomRepository _repository;

        public RoomController(IRoomRepository repository){
            _repository = repository;
        }

        public PartialViewResult RoomsForSelectedHotel(int id){
            var rooms = _repository.Find(r => r.HotelID == id).OrderBy(r => r.RoomID).AsEnumerable();
            return PartialView(rooms);
        }

        public PartialViewResult LatestRooms(){
            var rooms = _repository.LatestRooms();
            return PartialView(rooms);
        }

        public ActionResult SelectedRoom(int id){
            Room room = _repository.GetRoomWithPhotos(id);
            if (room != null){
                SelectedRoomJsonViewModel viewModel = new SelectedRoomJsonViewModel(){
                    RoomID = room.RoomID,
                    Name = room.Name,
                    Price = room.Price,
                    AdultsCapacity = room.Capacity,
                    KidsCapacity = room.KidsCapacity,
                    PhotoIds = room.Photos.Select(p => new PhotoViewModel(){PhotoID = p.PhotoID, IsPrimaryPhoto = p.IsPrimaryPhoto}).OrderByDescending(p => p.IsPrimaryPhoto).ToArray()
                };
                string jsonResult = JsonConvert.SerializeObject(viewModel);
                return Content(jsonResult,"application/json");
            }
            else{
                return HttpNotFound("Nie ma takiego pokoju");
            }
        }

    }
}

BookMe.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.Action("Search","Home")


<h2>Najnowsze hotele:</h2>
@Html.Action("LatestHotels", "Hotel")
<div class="row">
    <div class="col-md-6">
        <h2>Najpopularniejsze miasta:</h2>
        @Html.Action("MostPopularCities", "City")
    </div>
    <div class="col-md-6">
        <div class="row">
            <h2>Najnowsze pokoje:</h2>
            @Html.Action("LatestRooms", "Room")
        </div>
    </div>
</div>

BookMe.WebUI/Views/Home/Search.cshtml
@using System.Web.Optimization
@model BookMe.WebUI.Models.SearchViewModel


<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
            @using (@Html.BeginForm("List", "Hotel", FormMethod.Get, new { @class = "form-horizontal"})) {
                <div class="form-group col-sm-12">
                    <label for="search" class="col-sm-4 control-label">Cel podróży:</label>
                    <div class="col-sm-8">
                        @Html.TextBox("search", @Model.Search, null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label for="startDate" class="col-sm-4 control-label">Data przyjazdu:</label>
                    <div class="col-sm-8">
                        <div class="input-group date" id="datetimepicker">
                            @Html.TextBox("startDate", null, new { @class = "form-control" })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label for="endDate" class="col-sm-4 control-label">Data wyjazdu:</label>
                    <div class="col-sm-8">
                        <div class="input-group date" id="datetimepicker1">
                            @Html.TextBox("endDate", null, new { @class = "form-control" })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-sm-12">
                    <span class="col-sm-4" id="emptyLabel"></span>
                    <div class="col-sm-8" id="capacitySection">
                        <div class="form-group row" id="groupingDiv">
                            <label id="adultLabel" for="adultsInRoom" class="col-sm-2 control-label">Dorośli:</label>
                            <div class="col-sm-2" id="adultNumber">
                                @Html.TextBox("adultsInRoom", @Model.Adults, null, new { @class = "form-control", type = "number", min = @Model.MinAdultCapacity, max = @Model.MaxAdultCapacity })
                            </div>
                            <label id="kidsLabel" for="kidsInRoom" class="col-sm-2 control-label">Dzieci:</label>
                            <div class="col-sm-2" id="kidsNumber">
                                @Html.TextBox("kidsInRoom", @Model.Kids, null, new { @class = "form-control", type = "number", min = 0, max = @Model.MaxKidCapacity })
                            </div>
                        </div>
                    </div>
                </div>
                <input type="submit" value="Search" class="btn btn-default center-block" />
            }
    </div>
    <div class="col-md-2"></div>
</div>
@Scripts.Render("~/js")
<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datepicker();
        $('#datetimepicker1').datepicker();
    });

</script>