BookMe.WebUI/Models/LatestHotelsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Entities;

namespace BookMe.WebUI.Models {
    public class LatestHotelsViewModel {
        public Hotel Hotel { get; set; }
        public HttpPostedFileBase Image { get; set; }
    }
}

BookMe.WebUI/Controllers/HotelController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.Domain.Entities;
using BookMe.WebUI.Filters;
using BookMe.WebUI.Models;
using Ninject.Infrastructure.Language;

namespace BookMe.WebUI.Controllers {
    public class HotelController : Controller {
        private IHotelRepository _repository;
        public int PageSize { get; set; }
        public HotelController(IHotelRepository repository) {
            _repository = repository;
            PageSize = 3;
        }

        public ViewResult List(string search = null, DateTime? startDate = null, DateTime? endDate = null, int? adultsInRoom = null, int kidsInRoom = 0, int page = 1){
            IEnumerable<Hotel> hotels = _repository.GetHotelsFilteredBySearchDatesAdultsKidsInRoom(
                                                        search, startDate, endDate, adultsInRoom, kidsInRoom, page, PageSize);
            HotelListViewModel hotelListViewModel = new HotelListViewModel(){
                Hotels = hotels,
                PagingInfo = new PagingInfo(){
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.GetHotelsFilteredBySearchDatesAdultsKidsInRoom(search, startDate, endDate, adultsInRoom, kidsInRoom).Count()
                },
                SearchParameter = search,
                ChoosenArrival = startDate,
                ChoosenDeparture = endDate,
                KidsCapacity = kidsInRoom,
                AdultsCapacity = adultsInRoom
            };
            return View(hotelListViewModel);
        }
        public PartialViewResult LatestHotels() {
            return PartialView(_repository.LatestHotels());
        }

        public ActionResult Hotel(int id) {
            Hotel hotel = _repository.Get(id);
            if (hotel != null) {
                return View(hotel);
            } else {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

BookMe.WebUI/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookMe.Domain.Concrete.Repository.Interfaces;

namespace BookMe.WebUI.Controllers
{
    public class PhotoController : Controller{
        private IPhotoRepository _repository;

        public PhotoController(IPhotoRepository repository){
            _repository = repository;
        }

        // GET: Photo
        public ActionResult Index(int id){
            var photo = _repository.Get(id);
            return File(photo.ImageData, photo.ImageMimeType);
        }
    }
}

BookMe.WebUI/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BookMe.Domain.Concrete.Repository.Interfaces;
using BookMe.Domain.Entities;
using BookMe.WebUI.Models;
using Newtonsoft.Json;

namespace BookMe.WebUI.Controllers {
    public class RoomController : Controller{
        private IRoomRepository _repository;

        public RoomController(IRoomRepository repository){
            _repository = repository;
        }

        public PartialViewResult RoomsForSelectedHotel(int id){
            var rooms = _repository.Find(r => r.HotelID == id).OrderBy(r => r.RoomID).AsEnumerable();
            return PartialView(rooms);
        }

        public PartialViewResult LatestRooms(){
            var rooms = _repository.LatestRooms();
            return PartialView(rooms);
        }

        public ActionResult SelectedRoom(int id){
            Room room = _repository.GetRoomWithPhotos(id);
            if (room != null){
                SelectedRoomJsonViewModel viewModel = new SelectedRoomJsonViewModel(){
                    RoomID = room.RoomID,
                    Name = room.Name,
                    Price = room.Price,
                    AdultsCapacity = room.Capacity,
                    KidsCapacity = room.KidsCapacity,
                    PhotoIds = room.Photos.Select(p => new PhotoViewModel(){PhotoID = p.PhotoID, IsPrimaryPhoto = p.IsPrimaryPhoto}).OrderByDescending(p => p.IsPrimaryPhoto).ToArray()
                };
                string jsonResult = JsonConvert.SerializeObject(viewModel);
                return Content(jsonResult,"application/json");
            }
            else{
                return HttpNotFound("Nie ma takiego pokoju");
            }
        }

    }
}

BookMe.WebUI/Views/Hotel/Hotel.cshtml
@using System.Web.Optimization
@model BookMe.Domain.Entities.Hotel

@{
    ViewBag.Title = @Model.Name;
}
<div class="row">
    <div class="col-md-4">
        @Html.Action("Search","Home")
    </div>
    <div class="col-md-8">
        <div class="well">
            <div class="row">
                <div class="col-md-4">
                    @if (Model.Photos.Count != 0) {
                        <img src="@Url.Action("Index", "Photo", new{id = Model.Photos.First().PhotoID})" alt="@Model.Name@Model.City.Name" class="img-responsive" />
                    }
                </div>
                <div class="col-md-8">
                    <h2>@Model.Name</h2>
                    <strong>@Model.City.Name, @Model.City.ZipCode</strong>
                </div>
            </div>
        </div>

        <div class="modal fade" role="dialog" id="testModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>
                    <div class="modal-body" id="modalBody">
                        <div class="row">
                            <div class="col-sm-6 col-md-6" id="picturesColumn">
                                <div class="row">
                                    <div class="col-sm-12 col-md-12" id="mainImg"></div>
                                </div>
                                <div class="row" id="optionalImg" style="margin-top:15px">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6" id="dataColumn">
                                <table class="table">
                                    <tr>
                                        <td>Nazwa:</td>
                                        <td id="roomName" room-id=""></td>
                                    </tr>
                                    <tr>
                                        <td>Ilość dorosłych:</td>
                                        <td id="adultsCapacity"></td>
                                    </tr>
                                    <tr id="kidsCapacityRow">
                                    </tr>
                                    <tr>
                                        <td>Cena za noc:</td>
                                        <td id="price"></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    </div>
                </div>
            </div>
        </div>
        @Html.Action("RoomsForSelectedHotel", "Room", new { id = @Model.HotelID })
    </div>
</div>

<script type="text/javascript">
    $(document)
        .ready(function () {
            var loc = window.location.href;
            var patt = new RegExp("/Hotel/Hotel/")
            if (patt.test(loc)) {
                $('#emptyLabel').remove();
                $('#capacitySection').switchClass("col-sm-8", "");
                $('#groupingDiv').switchClass("form-group row", "form-group");
                $('#adultLabel').switchClass("col-sm-2", "col-sm-4");
                $('#adultNumber').switchClass("col-sm-2", "col-sm-8");
                $('#kidsLabel').switchClass("col-sm-2", "col-sm-4");
                $('#kidsNumber').switchClass("col-sm-2", "col-sm-8");
            }
        });
    $('.classForSelect')
        .click(function(e) {
            e.preventDefault();
            var id = $(this).attr("room-id");
            $.ajax({
                type: "GET",
                url: '@Url.Action("SelectedRoom","Room")',
                data: { id: id },
                dataType: 'json',
                success: function(data) {
                    $('#roomName').append("<b>" + data.Name + "</b>");
                    $('#roomName').attr("room-id", data.RoomID);
                    $('#adultsCapacity').append("<b>" + data.AdultsCapacity + "</b>");
                    if (data.KidsCapacity != '0') {

                        $('#kidsCapacityRow')
                            .html("<td id=\"kidsCapacity\">Ilość dzieci:</td>\n<td><b>" +
                                data.KidsCapacity +
                                "</b></td>");
                    }
                    $('#price').append("<b>" + data.Price + "</b>");
                    var photosCount = Object.keys(data.PhotoIds).length;
                    if (photosCount === 1 || photosCount === 2) {
                        console.log("Jesteś w ifie: photosCount == 1 lub photosCount == 2");
                        var url = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[0].PhotoID;
                        console.log("Main img: " + data.PhotoIds[0].PhotoID);
                        $('#mainImg').append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + url + "\"/>");
                    }
                    if (photosCount === 3) {
                        console.log("Jesteś w ifie: photosCount === 3");
                        var url = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[0].PhotoID;
                        $('#mainImg').append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + url + "\"/>");
                        $('#optionalImg')
                            .append("<div class=\"col-sm-6 col-md-6\" id=\"optional1\"></div>\n<div class=\"col-sm-6 col-md-6\" id=\"optional2\"></div>");
                        var urlOptional1 = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[1].PhotoID;
                        $('#optional1')
                            .append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + urlOptional1 + "\"/>");
                        var urlOptional2 = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[2].PhotoID;
                        $('#optional2')
                            .append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + urlOptional2 + "\"/>");
                    }
                    if (photosCount > 3) {
                        console.log("Jesteś w ifie photosCount > 3");
                        var url = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[0].PhotoID;
                        console.log("MainImg: " + data.PhotoIds[0].PhotoID);
                        $('#mainImg').append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + url + "\"/>");
                        $('#optionalImg')
                            .append("<div class=\"col-sm-4 col-md-4\" id=\"optional1\"></div>\n<div class=\"col-sm-4 col-md-4\" id=\"optional2\"></div>" +
                                "\n<div id=\"optional3\" class=\"col-sm-4 col-md-4\"></div>");
                        var urlOptional1 = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[1].PhotoID;
                        $('#optional1')
                            .append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + urlOptional1 + "\"/>");
                        var urlOptional2 = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[2].PhotoID;
                        $('#optional2')
                            .append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + urlOptional2 + "\"/>");
                        var urlOptional3 = '@Url.Action("Index","Photo")?id=' + data.PhotoIds[3].PhotoID;
                        $('#optional3')
                            .append("<img class=\"img-responsive\" alt=\"picture\" src=\"" + urlOptional3 + "\"/>");
                    }
                }
            });
        });

    $('.modal')
        .on("hidden.bs.modal",
            function () {
                $('#mainImg').html("");
                $('#optionalImg').html("");
                $('#roomName').html("");
                $('#roomName').attr("room-id", "");
                $('#adultsCapacity').html("");
                $('#kidsCapacity').html("");
                $('#price').html("");
            });
</script>

BookMe.WebUI/Views/Hotel/LatestHotels.cshtml
@using BookMe.Domain.Entities
@model IEnumerable<Hotel>
@{
    ViewBag.Title = "LatestHotels";
}
<div class="row">
    @foreach (var hotel in Model){
        @Html.Partial("HotelSummary",hotel)
    }
</div>

BookMe.WebUI/Views/Hotel/List.cshtml
@using BookMe.WebUI.HtmlHelpers
@using Castle.Core.Internal
@model BookMe.WebUI.Models.HotelListViewModel

@{
    ViewBag.Title = "Hotels";
}
@Html.Action("Search", "Home")
<h2>
    Wynik wyszukiwania dla:
    @if (!Model.SearchParameter.IsNullOrEmpty()) {
        @($"{Model.SearchParameter},");
    }
    @if (Model.ChoosenArrival != null && Model.ChoosenDeparture != null) {
        @($"przyjazd: {Model.ChoosenArrival.Value.ToShortDateString()}, odjazd {Model.ChoosenDeparture.Value.ToShortDateString()}, ");
    }
    @if (Model.AdultsCapacity != null) {
        @($"dorośli: {Model.AdultsCapacity}, ");
    }

    @($"dzieci: {Model.KidsCapacity}")
</h2>
@foreach (var hotel in Model.Hotels) {
    @*<h3>@Html.ActionLink(@hotel.Name,"Hotel","Hotel", new {id = @hotel.HotelID}, null)</h3>*@
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="thumbnail">
                <div class="row">
                    <div class="col-sm-5 col-md-5">
                        <img src="@Url.Action("Index", "Photo", new{id = hotel.Photos.FirstOrDefault().PhotoID})" alt="hotel" class="img-thumbnail" />
                    </div>
                    <div class="col-sm-7 col-md-7">
                        <div class="caption">
                            <h3>@Html.ActionLink(@hotel.Name,"Hotel","Hotel", new {id = @hotel.HotelID})</h3>
                            <p>@hotel.City.Name, @hotel.Address</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", "Hotel",
     new {
         page = x,
         search = Model.SearchParameter,
         startDate = Model.ChoosenArrival,
         endDate = Model.ChoosenDeparture,
         kidsInRoom = Model.KidsCapacity,
         adultsInRoom = Model.AdultsCapacity
     }, null))
</div>